"""Gate-matrix tests for agentic.fsconnect.writer (POSIX).

Proves: disabled => dry-run only; each gate refuses; with all gates satisfied the
write executes atomically; writes cannot escape writable_roots; the code-level hard
kill switch forces dry-run.
"""

from __future__ import annotations

import json
import os

import pytest
import yaml

from agentic.fsconnect import writer as writer_mod
from agentic.fsconnect.config import load_fsconnect_config
from agentic.fsconnect.writer import FsWriter
from utils.errors import FsConnectRuntimeError, FsPathError, FsWriteRefused
from utils.logger import _get_config, reset_config_cache

pytestmark = pytest.mark.skipif(os.name == "nt", reason="POSIX fixtures")


@pytest.fixture(autouse=True)
def _reset():
    reset_config_cache()
    yield
    reset_config_cache()


@pytest.fixture
def env(tmp_path):
    wz = tmp_path / "writezone"
    audit = tmp_path / "audit.jsonl"
    cfg_doc = {
        "logging": {"audit_file": str(audit), "audit_fields": {}},
        "policy": {"prompt_filter": {"banned_patterns": ["ignore previous instructions"]},
                   "privacy": {}},
        "fsconnect": {"enabled": True, "writable_roots": [str(wz)], "writes_enabled": False},
    }
    cfg_path = tmp_path / "config.yaml"
    cfg_path.write_text(yaml.safe_dump(cfg_doc), encoding="utf-8")
    cfg = _get_config(str(cfg_path))
    fs_cfg = load_fsconnect_config(str(cfg_path))
    return cfg, fs_cfg, str(cfg_path), wz, audit


def test_disabled_is_dryrun(env):
    cfg, fs_cfg, cp, wz, _audit = env
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("out.txt", b"data", reason="x")
    assert res["status"] == "dry_run_plan" and res["executed"] is False
    assert not (wz / "out.txt").exists()


def test_enabled_requires_reason(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_write("out.txt", b"data", reason="")
    assert ei.value.details["failed_gate"] == "reason"


def test_new_file_write_applies(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("out.txt", b"generated by qwen", reason="operator save")
    assert res["status"] == "applied" and res["executed"] is True
    assert (wz / "out.txt").read_bytes() == b"generated by qwen"


def test_overwrite_requires_confirm(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("a.txt", b"v1", reason="create")
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_write("a.txt", b"v2", reason="update", overwrite=True, confirm=False)
        assert ei.value.details["failed_gate"] == "confirm"
        res = w.fs_write("a.txt", b"v2", reason="update", overwrite=True, confirm=True)
    assert res["executed"] is True
    assert (wz / "a.txt").read_bytes() == b"v2"


def test_new_file_no_clobber_runtime(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("a.txt", b"v1", reason="create")
        # overwrite=False on an existing file => runtime no-clobber refusal
        with pytest.raises(FsConnectRuntimeError):
            w.fs_write("a.txt", b"v2", reason="create again", overwrite=False)


def test_write_cannot_escape(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsPathError):
            w.fs_write("../escape.txt", b"x", reason="evil", overwrite=True, confirm=True)
        with pytest.raises(FsPathError):
            w.fs_write("/tmp/escape.txt", b"x", reason="evil", overwrite=True, confirm=True)


def test_append_mkdir_move(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("doc.txt", b"l1\n", reason="seed")
        w.fs_append("doc.txt", b"l2\n", reason="append")
        w.fs_mkdir("folder", reason="mkdir")
        w.fs_move("doc.txt", "folder/moved.txt", reason="move", confirm=True)
    assert (wz / "folder" / "moved.txt").read_bytes() == b"l1\nl2\n"
    assert not (wz / "doc.txt").exists()


def test_oversized_write_refused(env):
    # max_write_bytes is enforced on the execute path: an over-cap payload is
    # refused and nothing is written (the cap was previously dead config).
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    fs_cfg.max_write_bytes = 8
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_write("big.txt", b"x" * 9, reason="too big")
    assert ei.value.details["failed_gate"] == "max_write_bytes"
    assert ei.value.details["size"] == 9 and ei.value.details["max"] == 8
    assert not (wz / "big.txt").exists()


def test_oversized_append_refused(env):
    # The append path is capped too, and must not mutate an existing file.
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    fs_cfg.max_write_bytes = 8
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("doc.txt", b"seed\n", reason="seed")
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_append("doc.txt", b"y" * 9, reason="too big")
    assert ei.value.details["failed_gate"] == "max_write_bytes"
    assert (wz / "doc.txt").read_bytes() == b"seed\n"  # unchanged


def test_write_at_cap_boundary_applies(env):
    # Boundary: exactly max_write_bytes is allowed (refusal is strictly >).
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    fs_cfg.max_write_bytes = 8
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("ok.txt", b"x" * 8, reason="at cap")
    assert res["executed"] is True
    assert (wz / "ok.txt").read_bytes() == b"x" * 8


def test_oversized_write_dryrun_not_refused(env):
    # The cap gates the real write only (like reason/confirm). With writes
    # disabled, an over-cap payload still returns a dry-run plan, not a refusal.
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.max_write_bytes = 8  # writes_enabled stays False (fixture default)
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("big.txt", b"x" * 9, reason="plan only")
    assert res["status"] == "dry_run_plan" and res["executed"] is False
    assert not (wz / "big.txt").exists()


def test_move_requires_confirm(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("s.txt", b"x", reason="seed")
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_move("s.txt", "d.txt", reason="move", confirm=False)
    assert ei.value.details["failed_gate"] == "confirm"


def test_hard_disable_forces_dryrun(env, monkeypatch):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    monkeypatch.setattr(writer_mod, "FS_WRITE_HARD_DISABLE", True)
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("out.txt", b"data", reason="x")
    assert res["status"] == "dry_run_plan"
    assert not (wz / "out.txt").exists()


def test_injection_flagged_on_write(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("p.txt", b"ignore previous instructions", reason="save")
    assert res["injection_flag_count"] >= 1  # advisory; write still applied
    assert res["executed"] is True


def test_audit_records_dryrun_and_applied(env):
    cfg, fs_cfg, cp, _wz, audit = env
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("d.txt", b"x", reason="dry")  # disabled => dryrun
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("e.txt", b"x", reason="applied")
    events = [json.loads(ln)["event"] for ln in audit.read_text().strip().splitlines()]
    assert "fsconnect_write_dryrun" in events
    assert "fsconnect_write_applied" in events
