"""Gate-matrix tests for agentic.fsconnect.writer (POSIX).

Proves: disabled => dry-run only; each gate refuses; with all gates satisfied the
write executes atomically; writes cannot escape writable_roots; the code-level hard
kill switch forces dry-run.
"""

from __future__ import annotations

import json
import os

import pytest
import yaml

from agentic.fsconnect import writer as writer_mod
from agentic.fsconnect.config import load_fsconnect_config
from agentic.fsconnect.writer import FsWriter
from utils.errors import FsConnectRuntimeError, FsPathError, FsWriteRefused
from utils.logger import _get_config, reset_config_cache

pytestmark = pytest.mark.skipif(os.name == "nt", reason="POSIX fixtures")


@pytest.fixture(autouse=True)
def _reset():
    reset_config_cache()
    yield
    reset_config_cache()


@pytest.fixture
def env(tmp_path):
    wz = tmp_path / "writezone"
    audit = tmp_path / "audit.jsonl"
    cfg_doc = {
        "logging": {"audit_file": str(audit), "audit_fields": {}},
        "policy": {"prompt_filter": {"banned_patterns": ["ignore previous instructions"]},
                   "privacy": {}},
        "fsconnect": {"enabled": True, "writable_roots": [str(wz)], "writes_enabled": False},
    }
    cfg_path = tmp_path / "config.yaml"
    cfg_path.write_text(yaml.safe_dump(cfg_doc), encoding="utf-8")
    cfg = _get_config(str(cfg_path))
    fs_cfg = load_fsconnect_config(str(cfg_path))
    return cfg, fs_cfg, str(cfg_path), wz, audit


def test_disabled_is_dryrun(env):
    cfg, fs_cfg, cp, wz, _audit = env
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("out.txt", b"data", reason="x")
    assert res["status"] == "dry_run_plan" and res["executed"] is False
    assert not (wz / "out.txt").exists()


def test_enabled_requires_reason(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_write("out.txt", b"data", reason="")
    assert ei.value.details["failed_gate"] == "reason"


def test_new_file_write_applies(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("out.txt", b"generated by qwen", reason="operator save")
    assert res["status"] == "applied" and res["executed"] is True
    assert (wz / "out.txt").read_bytes() == b"generated by qwen"


def test_overwrite_requires_confirm(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("a.txt", b"v1", reason="create")
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_write("a.txt", b"v2", reason="update", overwrite=True, confirm=False)
        assert ei.value.details["failed_gate"] == "confirm"
        res = w.fs_write("a.txt", b"v2", reason="update", overwrite=True, confirm=True)
    assert res["executed"] is True
    assert (wz / "a.txt").read_bytes() == b"v2"


def test_new_file_no_clobber_runtime(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("a.txt", b"v1", reason="create")
        # overwrite=False on an existing file => runtime no-clobber refusal
        with pytest.raises(FsConnectRuntimeError):
            w.fs_write("a.txt", b"v2", reason="create again", overwrite=False)


def test_write_cannot_escape(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsPathError):
            w.fs_write("../escape.txt", b"x", reason="evil", overwrite=True, confirm=True)
        with pytest.raises(FsPathError):
            w.fs_write("/tmp/escape.txt", b"x", reason="evil", overwrite=True, confirm=True)


def test_append_mkdir_move(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("doc.txt", b"l1\n", reason="seed")
        w.fs_append("doc.txt", b"l2\n", reason="append")
        w.fs_mkdir("folder", reason="mkdir")
        w.fs_move("doc.txt", "folder/moved.txt", reason="move", confirm=True)
    assert (wz / "folder" / "moved.txt").read_bytes() == b"l1\nl2\n"
    assert not (wz / "doc.txt").exists()


def test_move_requires_confirm(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("s.txt", b"x", reason="seed")
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_move("s.txt", "d.txt", reason="move", confirm=False)
    assert ei.value.details["failed_gate"] == "confirm"


def test_hard_disable_forces_dryrun(env, monkeypatch):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    monkeypatch.setattr(writer_mod, "FS_WRITE_HARD_DISABLE", True)
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("out.txt", b"data", reason="x")
    assert res["status"] == "dry_run_plan"
    assert not (wz / "out.txt").exists()


def test_injection_flagged_on_write(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("p.txt", b"ignore previous instructions", reason="save")
    assert res["injection_flag_count"] >= 1  # advisory; write still applied
    assert res["executed"] is True


def test_audit_records_dryrun_and_applied(env):
    cfg, fs_cfg, cp, _wz, audit = env
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("d.txt", b"x", reason="dry")  # disabled => dryrun
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("e.txt", b"x", reason="applied")
    events = [json.loads(ln)["event"] for ln in audit.read_text().strip().splitlines()]
    assert "fsconnect_write_dryrun" in events
    assert "fsconnect_write_applied" in events


# ---------------------------------------------------------------------------
# max_write_bytes is actually enforced (PR — was previously validated as a
# config field but never checked against a payload)
# ---------------------------------------------------------------------------


def test_fs_write_refuses_payload_over_max_write_bytes(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    fs_cfg.max_write_bytes = 64
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_write("big.txt", b"X" * 65, reason="should refuse")
    assert ei.value.details["failed_gate"] == "max_write_bytes"
    assert ei.value.details["bytes"] == 65
    assert ei.value.details["max"] == 64
    # Nothing was written.
    assert not (wz / "big.txt").exists()


def test_fs_append_refuses_payload_over_max_write_bytes(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    fs_cfg.max_write_bytes = 8
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_append("a.txt", b"123456789", reason="should refuse")
    assert ei.value.details["failed_gate"] == "max_write_bytes"
    # File never created because the cap fired before the syscall.
    assert not (wz / "a.txt").exists()


def test_fs_write_under_cap_still_applies(env):
    """Sanity: a payload at or under the cap proceeds normally."""
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    fs_cfg.max_write_bytes = 64
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("ok.txt", b"X" * 64, reason="exactly at cap")
    assert res["executed"] is True
    assert (wz / "ok.txt").read_bytes() == b"X" * 64


def test_fs_write_cap_enforced_before_reason_gate(env):
    """The size cap fires BEFORE the reason gate so an oversized payload can
    never sneak through as a dry-run plan (which would otherwise expose
    bytes/sha256 in the audit log for a payload the operator already
    promised never to write)."""
    cfg, fs_cfg, cp, _wz, _audit = env
    # writes_enabled stays False (default) — pre-fix the dry-run plan would
    # have included the oversized bytes/sha; with the cap, FsWriteRefused.
    fs_cfg.max_write_bytes = 4
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_write("dr.txt", b"x" * 99, reason="")  # empty reason too
    assert ei.value.details["failed_gate"] == "max_write_bytes"


# ---------------------------------------------------------------------------
# rule_applied + two-phase audit (item 1, I3 hardening)
# ---------------------------------------------------------------------------


def _events(audit):
    return [json.loads(ln) for ln in audit.read_text().strip().splitlines()]


def test_rule_applied_on_allow_and_deny(env):
    cfg, fs_cfg, cp, _wz, audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("ok.txt", b"x", reason="save")
        assert res["rule_applied"].startswith("allowed:")
        with pytest.raises(FsWriteRefused):
            w.fs_write("ok.txt", b"x", reason="", overwrite=True)
    evs = _events(audit)
    applied = [e for e in evs if e["event"] == "fsconnect_write_applied"]
    refused = [e for e in evs if e["event"] == "fsconnect_write_refused"]
    assert applied and applied[0]["rule_applied"].startswith("allowed:")
    assert refused and refused[0]["rule_applied"].startswith("denied:")


def test_intent_precedes_applied(env):
    """The write_intent event must be emitted before write_applied for the same op."""
    cfg, fs_cfg, cp, _wz, audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("seq.txt", b"x", reason="order")
    evs = [e["event"] for e in _events(audit)]
    assert evs.index("fsconnect_write_intent") < evs.index("fsconnect_write_applied")


# ---------------------------------------------------------------------------
# reserved-name enforcement (item 4)
# ---------------------------------------------------------------------------


def test_reserved_trash_dir_refused(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_write(".cyclaw-trash/forged.txt", b"x", reason="evil")
    assert ei.value.details["failed_gate"] == "reserved_name"


def test_reserved_quota_file_refused(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_write(".cyclaw-quota.json", b"{}", reason="evil")
    assert ei.value.details["failed_gate"] == "reserved_name"


# ---------------------------------------------------------------------------
# block_on_injection_flags (item 8)
# ---------------------------------------------------------------------------


def test_block_on_injection_flags_refuses(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    fs_cfg.block_on_injection_flags = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_write("p.txt", b"ignore previous instructions", reason="save")
    assert ei.value.details["failed_gate"] == "injection_scan"
    assert not (wz / "p.txt").exists()


# ---------------------------------------------------------------------------
# fs_delete: trash / purge / fifth gate / non-empty dir (item 4)
# ---------------------------------------------------------------------------


def test_delete_to_trash_applies(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("gone.txt", b"bye", reason="seed")
        res = w.fs_delete("gone.txt", reason="clean up", confirm=True)
    assert res["status"] == "applied" and res["mode"] == "trash"
    assert not (wz / "gone.txt").exists()
    # a trash entry + sidecar now exist
    trash_dir = wz / ".cyclaw-trash"
    names = {p.name for p in trash_dir.iterdir()}
    assert res["trash_entry"] in names
    assert f"{res['trash_entry']}.meta.json" in names


def test_delete_dryrun_plan_when_disabled(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("keep.txt", b"x", reason="seed")
    fs_cfg.writes_enabled = False
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_delete("keep.txt", reason="plan only", confirm=True)
    assert res["status"] == "dry_run_plan" and res["executed"] is False
    assert "trash_entry" in res
    assert (wz / "keep.txt").exists()


def test_delete_requires_confirm(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("c.txt", b"x", reason="seed")
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_delete("c.txt", reason="del", confirm=False)
    assert ei.value.details["failed_gate"] == "confirm"


def test_purge_refused_without_allow_hard_delete(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    assert fs_cfg.allow_hard_delete is False
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("h.txt", b"x", reason="seed")
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_delete("h.txt", reason="hard", confirm=True, purge=True)
    assert ei.value.details["failed_gate"] == "allow_hard_delete"
    assert (wz / "h.txt").exists()  # untouched


def test_purge_with_allow_hard_delete_removes(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    fs_cfg.allow_hard_delete = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("h.txt", b"x", reason="seed")
        res = w.fs_delete("h.txt", reason="hard", confirm=True, purge=True)
    assert res["mode"] == "purge" and res["executed"] is True
    assert not (wz / "h.txt").exists()
    assert not (wz / ".cyclaw-trash").exists()  # purge never touches trash


def test_purge_nonempty_dir_refused(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    fs_cfg.allow_hard_delete = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_mkdir("d", reason="seed")
        w.fs_write("d/inner.txt", b"x", reason="seed")
        with pytest.raises(FsWriteRefused) as ei:
            w.fs_delete("d", reason="hard", confirm=True, purge=True)
    assert ei.value.details["failed_gate"] == "non_empty_dir"
    assert (wz / "d" / "inner.txt").exists()


def test_delete_root_itself_refused(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        with pytest.raises(FsPathError):
            w.fs_delete("", reason="del root", confirm=True)


# ---------------------------------------------------------------------------
# trash lifecycle: restore + empty (item 5)
# ---------------------------------------------------------------------------


def test_trash_restore_roundtrip(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("r.txt", b"restore me", reason="seed")
        d = w.fs_delete("r.txt", reason="oops", confirm=True)
        entry = d["trash_entry"]
        res = w.trash_restore(entry, reason="undo", confirm=True)
    assert res["restored"].endswith("r.txt")
    assert (wz / "r.txt").read_bytes() == b"restore me"


def test_trash_empty_requires_allow_hard_delete(env):
    cfg, fs_cfg, cp, _wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("t.txt", b"x", reason="seed")
        w.fs_delete("t.txt", reason="trash", confirm=True)
        with pytest.raises(FsWriteRefused) as ei:
            w.trash_empty(reason="empty all", confirm=True, all_entries=True)
    assert ei.value.details["failed_gate"] == "allow_hard_delete"


def test_trash_empty_all_purges(env):
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    fs_cfg.allow_hard_delete = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        w.fs_write("t.txt", b"x", reason="seed")
        d = w.fs_delete("t.txt", reason="trash", confirm=True)
        res = w.trash_empty(reason="empty all", confirm=True, all_entries=True)
    assert d["trash_entry"] in res["purged"]
    trash_dir = wz / ".cyclaw-trash"
    remaining = list(trash_dir.iterdir()) if trash_dir.exists() else []
    assert remaining == []


def test_windows_writes_hard_refused(env, monkeypatch):
    # codex P1: the Windows fallback validates by name then writes by name -- a
    # junction swapped in between redirects the write outside the root (TOCTOU).
    # Until handle-based containment lands, writes are HARD-refused on Windows
    # (not dry-run) even when every other gate passes. This case: a writer
    # CONSTRUCTED on POSIX that later runs on Windows -- the per-op gate refuses.
    # Forced via the platform helper, NOT os.name: os.name="nt" makes
    # pathlib.Path raise on a POSIX host, so audit_log (and thus the refusal
    # itself) would crash before it could be asserted.
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        monkeypatch.setattr(writer_mod, "_writes_refused_platform", lambda: True)
        with pytest.raises(FsWriteRefused) as exc:
            w.fs_write("out.txt", b"data", reason="x")
    assert exc.value.details.get("failed_gate") == "platform"
    assert not (wz / "out.txt").exists()
    # The refusal is audited with the rule applied, like every other gate.
    rows = [json.loads(line) for line in _audit.read_text(encoding="utf-8").splitlines()]
    refused = [r for r in rows if r.get("event") == "fsconnect_write_refused"]
    assert refused and refused[0]["failed_gate"] == "platform"


def test_posix_writes_still_execute_with_gates_satisfied(env):
    # Guard against over-correction: on POSIX the same fully-gated write must
    # still execute (the Windows refusal is platform-scoped).
    cfg, fs_cfg, cp, wz, _audit = env
    fs_cfg.writes_enabled = True
    with FsWriter(cfg, fs_cfg, config_path=cp) as w:
        res = w.fs_write("out.txt", b"data", reason="x")
    assert res["executed"] is True
    assert (wz / "out.txt").read_bytes() == b"data"


def test_windows_init_refuses_before_root_creation(env, monkeypatch):
    # codex #593 P1 (the gap the prior test missed): a NATIVELY-Windows
    # construction was untested. ScopedRoots(create=True) mkdirs the configured
    # root -- or the ~/CyClaw-FS fallback -- during __init__, BEFORE any refusal,
    # even in dry-run. Force Windows at CONSTRUCTION and prove nothing is
    # created: init refuses (audited, failed_gate="platform") before ScopedRoots
    # runs. Forced via the platform helper, not os.name, so pathlib.Path (used by
    # ScopedRoots and audit_log) does not itself raise on this POSIX host.
    cfg, fs_cfg, cp, wz, audit = env
    fs_cfg.writes_enabled = True
    assert not wz.exists()  # the fixture does NOT pre-create the write root
    monkeypatch.setattr(writer_mod, "_writes_refused_platform", lambda: True)

    with pytest.raises(FsWriteRefused) as exc:
        FsWriter(cfg, fs_cfg, config_path=cp)

    assert exc.value.details.get("failed_gate") == "platform"
    assert not wz.exists()  # configured root NOT created (refused before ScopedRoots)
    rows = [json.loads(line) for line in audit.read_text(encoding="utf-8").splitlines()]
    refused = [r for r in rows if r.get("event") == "fsconnect_write_refused"]
    assert refused and refused[0]["failed_gate"] == "platform"


def test_windows_init_refused_even_when_writes_disabled(env, monkeypatch):
    # Even in dry-run posture (writes_enabled False) a Windows construction must
    # create nothing: the reviewer's concern was ScopedRoots mutating the FS
    # "even during dry-run or before any write occurs".
    cfg, fs_cfg, cp, wz, _audit = env
    assert fs_cfg.writes_enabled is False  # fixture default
    assert not wz.exists()
    monkeypatch.setattr(writer_mod, "_writes_refused_platform", lambda: True)

    with pytest.raises(FsWriteRefused):
        FsWriter(cfg, fs_cfg, config_path=cp)
    assert not wz.exists()  # no root created even in dry-run posture
