#!/usr/bin/env bash
# setup-cyclaw.sh — friendly one-command CyClaw onboarding for Apple Silicon.
#
# This is the operator-facing entrypoint. It deliberately composes the existing
# hardened macos/ helpers rather than duplicating installation or secret-store
# logic:
#
#   setup-from-clone.sh    install + Ollama + retrieval index
#   setup-cyclaw-keys.sh   API-key generation, prompts, and persistence
#   invoke-cyclaw.sh       gateway :8787 + coding harness :8790
#
# CYCLAW_API_KEY is generated by setup-cyclaw-keys.sh with
# `openssl rand -hex 20`, then persisted to macOS Keychain and a chmod-600
# dotenv. Optional provider keys remain skippable. If browser population is
# selected, the already-running server key is injected only into the terminal
# and harness input elements on 127.0.0.1; it is never written to localStorage
# or a cookie.
#
# Usage:
#   bash macos/setup-cyclaw.sh
#   bash macos/setup-cyclaw.sh --small-model
#   bash macos/setup-cyclaw.sh --skip-prompts --grok-dummy --start --fill-browser
#   bash macos/setup-cyclaw.sh --dry-run --fill-browser
#
# Onboarding options:
#   --start               start gateway + harness after setup
#   --no-start            finish installation without starting servers
#   --fill-browser        populate CYCLAW_API_KEY into both loopback consoles
#   --no-fill-browser     do not populate browser fields
#   --no-browser          do not open CyClaw console tabs (implies no fill)
#
# Install options forwarded to setup-from-clone.sh:
#   --skip-install
#   --skip-python-deps
#   --skip-keys
#   --skip-ollama
#   --skip-index
#   --skip-advisor
#   --no-fsconnect
#   --no-profile-edit
#   --no-path-edit
#   --grok-dummy
#   --rotate-key
#   --small-model
#   --ollama-model TAG
#   --ollama-install-script
#   --skip-prompts | --yes
#   --dry-run
#   --help
#
# Target: macOS 14+ on Apple Silicon (arm64), bash 3.2 / zsh, BSD userland.
#
# Privacy and safety:
#   - never prints a secret value
#   - never places a secret on a child-process argv
#   - never writes a secret to config.yaml, a plist, or a shell profile
#   - keeps fsconnect writes/indexing off
#   - does not generate or load LaunchAgents
#   - never touches soul.md
#   - remains out of the gate.py / graph.py request path (I6)

set -euo pipefail

step() { printf '[cyclaw] %s\n' "$1"; }
warn() { printf '[cyclaw] WARNING: %s\n' "$1" >&2; }
die()  { printf '[cyclaw] error: %s\n' "$1" >&2; exit 1; }

usage() {
  sed -n '3,60p' "$0" | sed 's/^# \{0,1\}//'
}

START_CHOICE="ask"
FILL_CHOICE="ask"
NO_BROWSER=0
SKIP_PROMPTS=0
DRY_RUN=0
SKIP_KEYS=0
DELEGATE_ARGS=()
KEY_ARGS=()

while [ $# -gt 0 ]; do
  case "$1" in
    --start)
      START_CHOICE="yes"
      shift
      ;;
    --no-start)
      START_CHOICE="no"
      shift
      ;;
    --fill-browser)
      FILL_CHOICE="yes"
      shift
      ;;
    --no-fill-browser)
      FILL_CHOICE="no"
      shift
      ;;
    --no-browser)
      NO_BROWSER=1
      shift
      ;;
    --skip-prompts|--yes)
      SKIP_PROMPTS=1
      DELEGATE_ARGS+=(--skip-prompts)
      KEY_ARGS+=(--skip-prompts)
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      DELEGATE_ARGS+=(--dry-run)
      shift
      ;;
    --skip-keys)
      SKIP_KEYS=1
      shift
      ;;
    --grok-dummy)
      KEY_ARGS+=(--grok-dummy)
      shift
      ;;
    --rotate-key)
      KEY_ARGS+=(--rotate)
      shift
      ;;
    --no-profile-edit)
      DELEGATE_ARGS+=(--no-profile-edit)
      KEY_ARGS+=(--no-profile-edit)
      shift
      ;;
    --ollama-model)
      DELEGATE_ARGS+=(--ollama-model "${2:?--ollama-model requires a tag}")
      shift 2
      ;;
    --skip-install|--skip-python-deps|--skip-ollama|--skip-index|--skip-advisor|\
    --no-fsconnect|--no-path-edit|--small-model|--ollama-install-script)
      DELEGATE_ARGS+=("$1")
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ "$FILL_CHOICE" = "yes" ] && [ "$NO_BROWSER" -eq 1 ]; then
  die "--fill-browser cannot be combined with --no-browser"
fi
if [ "$FILL_CHOICE" = "yes" ] && [ "$START_CHOICE" = "no" ]; then
  die "--fill-browser cannot be combined with --no-start"
fi

if [ "${CYCLAW_SETUP_FROM_CLONE_SKIP_PLATFORM:-}" != "1" ]; then
  if [ "$(uname -s)" != "Darwin" ]; then
    die "this onboarding script is for macOS Apple Silicon only (uname -s is $(uname -s))"
  fi
  if [ "$(uname -m)" != "arm64" ]; then
    die "Apple Silicon (arm64) is required; this Mac reports $(uname -m)"
  fi
  _macos_version="$(sw_vers -productVersion 2>/dev/null || true)"
  _macos_major="${_macos_version%%.*}"
  if [ -n "$_macos_major" ] && [ "$_macos_major" -lt 14 ] 2>/dev/null; then
    warn "macOS 14 Sonoma is the supported floor (detected ${_macos_version})"
  fi
fi

if [ "$SKIP_PROMPTS" -eq 0 ] && [ "$DRY_RUN" -eq 0 ] && [ ! -t 0 ]; then
  die "interactive onboarding needs a TTY; re-run in Terminal or pass --skip-prompts"
fi

_SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_DIR="$(CDPATH= cd -- "$_SCRIPT_DIR/.." && pwd)"
HOME_DIR="${CYCLAW_HOME:-$HOME/.CyClaw}"
GATE_PORT="${CYCLAW_GATE_PORT:-8787}"
HARNESS_PORT="${CYCLAW_HARNESS_PORT:-8790}"

require_port() {
  case "$2" in
    ''|*[!0-9]*)
      die "$1 requires a numeric port (got '$2')"
      ;;
  esac
  if [ "$2" -lt 1 ] || [ "$2" -gt 65535 ]; then
    die "$1 must be between 1 and 65535 (got '$2')"
  fi
}

require_port "gateway port (CYCLAW_GATE_PORT)" "$GATE_PORT"
require_port "harness port (CYCLAW_HARNESS_PORT)" "$HARNESS_PORT"

reject_shell_metachars() {
  case "$1" in
    *'"'*|*'`'*|*'$'*|*'\'*)
      die "refusing a path containing shell metacharacters (\", \`, \$, or \\): $1"
      ;;
  esac
}

reject_shell_metachars "$REPO_DIR"
reject_shell_metachars "$HOME_DIR"

for _required in \
  "$REPO_DIR/macos/setup-from-clone.sh" \
  "$REPO_DIR/macos/invoke-cyclaw.sh" \
  "$REPO_DIR/macos/setup-cyclaw-keys.sh" \
  "$REPO_DIR/gate.py" \
  "$REPO_DIR/harness/server.py"
do
  [ -f "$_required" ] || die "not a complete CyClaw checkout (missing $_required)"
done

_confirm() {
  local prompt="$1" default="${2:-y}" reply
  if [ "$default" = "y" ]; then
    printf '[cyclaw] %s [Y/n] ' "$prompt" >&2
  else
    printf '[cyclaw] %s [y/N] ' "$prompt" >&2
  fi
  IFS= read -r reply || true
  case "$reply" in
    "")
      [ "$default" = "y" ]
      ;;
    y|Y|yes|YES)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

SHOULD_START=0
case "$START_CHOICE" in
  yes)
    SHOULD_START=1
    ;;
  no)
    SHOULD_START=0
    ;;
  ask)
    if [ "$SKIP_PROMPTS" -eq 1 ]; then
      SHOULD_START=0
    elif [ "$DRY_RUN" -eq 1 ]; then
      SHOULD_START=1
    elif _confirm "Start the RAG gateway and coding harness when setup finishes?" "y"; then
      SHOULD_START=1
    fi
    ;;
esac

AUTO_FILL_BROWSER=0
case "$FILL_CHOICE" in
  yes)
    AUTO_FILL_BROWSER=1
    ;;
  no)
    AUTO_FILL_BROWSER=0
    ;;
  ask)
    if [ "$NO_BROWSER" -eq 0 ] && [ "$SHOULD_START" -eq 1 ]; then
      if [ "$DRY_RUN" -eq 1 ]; then
        AUTO_FILL_BROWSER=1
      elif [ "$SKIP_PROMPTS" -eq 0 ] && \
           _confirm "Populate the generated CYCLAW_API_KEY into the local terminal + harness fields after startup? (memory only; clipboard fallback clears after 90s)" "y"; then
        AUTO_FILL_BROWSER=1
      fi
    fi
    ;;
esac

if [ "$NO_BROWSER" -eq 1 ]; then
  AUTO_FILL_BROWSER=0
fi
if [ "$SHOULD_START" -eq 0 ] && [ "$AUTO_FILL_BROWSER" -eq 1 ]; then
  die "browser population requires the servers to start"
fi

echo ""
step "CyClaw macOS onboarding"
step "repo        : $REPO_DIR"
step "home        : $HOME_DIR"
if [ "$SKIP_KEYS" -eq 0 ]; then
  step "API key     : autogenerate + persist (Keychain and chmod-600 dotenv)"
else
  step "API key     : bootstrap skipped; use an existing persisted key"
fi
if [ "$SHOULD_START" -eq 1 ]; then
  step "start       : gateway :$GATE_PORT + harness :$HARNESS_PORT"
else
  step "start       : no"
fi
if [ "$AUTO_FILL_BROWSER" -eq 1 ]; then
  step "browser key : yes (loopback fields only; memory-only)"
elif [ "$NO_BROWSER" -eq 1 ]; then
  step "browser     : disabled"
else
  step "browser key : no"
fi
echo ""

if [ "$DRY_RUN" -eq 1 ]; then
  step "dry-run wrapper plan (no writes, no network):"
  echo "  1. delegate install, Ollama, and indexing to setup-from-clone.sh"
  echo "  2. force the delegate to skip keys and stop before server startup"
  if [ "$SKIP_KEYS" -eq 0 ]; then
    echo "  3. autogenerate CYCLAW_API_KEY and persist all selected keys via setup-cyclaw-keys.sh"
  else
    echo "  3. skip API-key bootstrap (--skip-keys)"
  fi
  if [ "$SHOULD_START" -eq 1 ]; then
    echo "  4. start invoke-cyclaw.sh with browser opening disabled"
    if [ "$AUTO_FILL_BROWSER" -eq 1 ]; then
      echo "  5. wait for both loopback services, then populate CYCLAW_API_KEY in memory"
    elif [ "$NO_BROWSER" -eq 0 ]; then
      echo "  5. wait for both loopback services, then open both consoles"
    fi
  fi
  echo ""
fi

# setup-from-clone.sh remains the owner of installation, Ollama, and index
# creation. Key bootstrap runs immediately afterward with --no-print-key so
# the generated operator key is persisted without being dumped to the terminal.
DELEGATE_ARGS+=(--skip-keys --no-start)
bash "$REPO_DIR/macos/setup-from-clone.sh" "${DELEGATE_ARGS[@]}"

if [ "$DRY_RUN" -eq 1 ]; then
  exit 0
fi

if [ "$SKIP_KEYS" -eq 0 ]; then
  step "bootstrapping API keys (CYCLAW_API_KEY is generated automatically)"
  KEY_ARGS=(--repo-path "$REPO_DIR" --no-print-key "${KEY_ARGS[@]}")
  bash "$REPO_DIR/macos/setup-cyclaw-keys.sh" "${KEY_ARGS[@]}"
else
  step "skipping API-key bootstrap (--skip-keys)"
fi

# A child process cannot export into this parent. Load the persisted dotenv so
# invoke-cyclaw.sh and the browser helper inherit the exact server key.
case "$-" in
  *x*)
    die "refusing to source a secrets dotenv while xtrace is enabled"
    ;;
esac
if [ -f "$HOME_DIR/.env" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$HOME_DIR/.env"
  set +a
  step "loaded $HOME_DIR/.env into this process (values not printed)"
elif [ -f "$REPO_DIR/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  . "$REPO_DIR/.env"
  set +a
  step "loaded $REPO_DIR/.env into this process (values not printed)"
fi

if [ "$SHOULD_START" -eq 0 ]; then
  echo ""
  step "setup complete; servers were not started"
  step "later: source $HOME_DIR/.env && bash macos/invoke-cyclaw.sh"
  exit 0
fi

if [ "$AUTO_FILL_BROWSER" -eq 1 ] && [ -z "${CYCLAW_API_KEY:-}" ]; then
  die "browser population was selected, but CYCLAW_API_KEY was not loaded; re-run without --skip-keys or source the existing dotenv"
fi

INVOKE_PID=""
FILL_HOME=""

cleanup() {
  trap - EXIT INT TERM
  if [ -n "$INVOKE_PID" ] && kill -0 "$INVOKE_PID" 2>/dev/null; then
    step "stopping CyClaw server supervisor (pid $INVOKE_PID)"
    kill "$INVOKE_PID" 2>/dev/null || true
    wait "$INVOKE_PID" 2>/dev/null || true
  fi
  if [ -n "$FILL_HOME" ] && [ -d "$FILL_HOME" ]; then
    rm -rf "$FILL_HOME"
  fi
  FILL_HOME=""
}

_on_int() {
  cleanup
  exit 130
}

_on_term() {
  cleanup
  exit 143
}

trap cleanup EXIT
trap _on_int INT
trap _on_term TERM

step "starting RAG gateway + coding harness"
bash "$REPO_DIR/macos/invoke-cyclaw.sh" \
  --repo "$REPO_DIR" \
  --gate-port "$GATE_PORT" \
  --port "$HARNESS_PORT" \
  --no-browser &
INVOKE_PID=$!

_services_ready=0
_attempt=0
while [ "$_attempt" -lt 60 ]; do
  _attempt=$((_attempt + 1))
  if ! kill -0 "$INVOKE_PID" 2>/dev/null; then
    if wait "$INVOKE_PID"; then
      _invoke_rc=0
    else
      _invoke_rc=$?
    fi
    INVOKE_PID=""
    die "CyClaw server supervisor exited during startup (status $_invoke_rc)"
  fi

  if curl -sf --max-time 1 http://127.0.0.1:$GATE_PORT/health >/dev/null 2>&1 && \
     curl -sf --max-time 1 http://127.0.0.1:$HARNESS_PORT/ >/dev/null 2>&1; then
    _services_ready=1
    break
  fi
  sleep 0.5
done

if [ "$_services_ready" -eq 1 ]; then
  step "gateway + harness are ready on loopback"
else
  warn "both consoles did not answer within 30 seconds; opening/filling once anyway"
fi

if [ "$NO_BROWSER" -eq 0 ]; then
  if [ "$AUTO_FILL_BROWSER" -eq 1 ]; then
    # setup-cyclaw-keys.sh normally prefers Keychain/.env. Use an empty,
    # temporary CYCLAW_HOME so this call consumes the exact environment key
    # inherited by the running servers. All persistence switches are disabled.
    # The key is inherited through the environment, never placed on argv.
    FILL_HOME="$(mktemp -d "${TMPDIR:-/tmp}/cyclaw-browser-fill.XXXXXX")"
    if CYCLAW_HOME="$FILL_HOME" bash "$REPO_DIR/macos/setup-cyclaw-keys.sh" \
        --repo-path "$REPO_DIR" \
        --skip-prompts \
        --no-print-key \
        --no-keychain \
        --no-env-file \
        --no-repo-env \
        --no-profile-edit \
        --fill-browser \
        --gate-port "$GATE_PORT" \
        --harness-port "$HARNESS_PORT"; then
      step "populated terminal + harness API-key fields (memory-only)"
    else
      warn "automatic browser fill failed; paste CYCLAW_API_KEY into the local fields manually"
    fi
    rm -rf "$FILL_HOME"
    FILL_HOME=""
  elif command -v open >/dev/null 2>&1; then
    open "http://127.0.0.1:$GATE_PORT" >/dev/null 2>&1 || true
    open "http://127.0.0.1:$HARNESS_PORT" >/dev/null 2>&1 || true
    step "opened terminal + harness consoles"
  fi
fi

echo ""
step "CyClaw is running"
step "terminal : http://127.0.0.1:$GATE_PORT"
step "harness  : http://127.0.0.1:$HARNESS_PORT"
step "stop     : Ctrl+C"
echo ""

if wait "$INVOKE_PID"; then
  _invoke_rc=0
else
  _invoke_rc=$?
fi
INVOKE_PID=""
trap - EXIT INT TERM
exit "$_invoke_rc"
