#!/usr/bin/env bash
# CyClaw macOS onboarding
#
# One operator-facing entry point for a fresh or existing CyClaw checkout.
# It delegates installation and primary secret persistence to the repository's
# existing hardened macOS helpers rather than creating a second secret system.
#
# What it adds:
#   - Can clone CyClaw when run outside a checkout.
#   - Presents start/browser/API-key autofill choices before installation.
#   - Ensures CYCLAW_API_KEY is autogenerated and persisted by
#     macos/setup-cyclaw-keys.sh.
#   - Optionally opens the loopback console and fills #apiKeyInput
#     in browser memory only. No localStorage, cookie, config.yaml, or argv secret.
#
# Target: macOS 14+ on Apple Silicon, bash 3.2 or newer.
#
# Typical use inside a clone:
#   bash macos/setup-cyclaw.sh
#
# Standalone use after downloading this file:
#   bash setup-cyclaw.sh
#
# Non-interactive example:
#   bash macos/setup-cyclaw.sh --skip-prompts --start --autofill-api-key
#
# This script is installer glue only. It does not alter soul.md, config gates,
# request-path topology, or agentic enablement.

set -euo pipefail

step() { printf '[cyclaw-onboard] %s\n' "$1"; }
warn() { printf '[cyclaw-onboard] WARNING: %s\n' "$1" >&2; }
die()  { printf '[cyclaw-onboard] ERROR: %s\n' "$1" >&2; exit 1; }

usage() {
  cat <<'EOF'
CyClaw macOS onboarding

Usage:
  bash macos/setup-cyclaw.sh [options]
  bash setup-cyclaw.sh [options]          # standalone downloaded copy

Onboarding options:
  --repo PATH              use an existing CyClaw checkout
  --clone-dir PATH         clone into PATH when no checkout is found
                           (default: ~/CyClaw)
  --start                  start the gateway after setup
  --no-start               install/configure only
  --browser                open the loopback console after startup
  --no-browser             do not open browser tabs
  --autofill-api-key       fill #apiKeyInput / #apiKey after startup
  --no-autofill-api-key    leave browser key fields empty
  --skip-prompts           non-interactive; optional secrets are skipped
  --dry-run                print the planned actions and exit
  --help

Forwarded to macos/setup-from-clone.sh:
  --skip-install
  --skip-python-deps
  --skip-keys
  --skip-ollama
  --skip-index
  --skip-privacy
  --no-fsconnect
  --no-profile-edit
  --no-path-edit
  --grok-dummy
  --rotate-key
  --small-model
  --ollama-model TAG
  --ollama-install-script

Security behavior:
  * CYCLAW_API_KEY is generated with openssl by the existing key helper.
  * Primary keys persist to macOS Keychain and ~/.CyClaw/.env (0600).
  * Browser autofill is restricted to 127.0.0.1 / ::1 CyClaw tabs.
  * The browser retains the key only in the input element; reload clears it.
  * Secret values are never printed or passed as child-process arguments.
EOF
}

START_MODE="ask"
BROWSER_MODE="ask"
AUTOFILL_MODE="ask"
SKIP_PROMPTS=0
DRY_RUN=0
REPO_OVERRIDE=""
CLONE_DIR="${HOME}/CyClaw"
SKIP_KEYS=0
FORWARD_ARGS=()

while [ "$#" -gt 0 ]; do
  case "$1" in
    --repo)
      REPO_OVERRIDE="${2:?--repo requires a path}"
      shift 2
      ;;
    --clone-dir)
      CLONE_DIR="${2:?--clone-dir requires a path}"
      shift 2
      ;;
    --start)
      START_MODE="yes"
      shift
      ;;
    --no-start)
      START_MODE="no"
      shift
      ;;
    --browser)
      BROWSER_MODE="yes"
      shift
      ;;
    --no-browser)
      BROWSER_MODE="no"
      shift
      ;;
    --autofill-api-key|--fill-browser)
      AUTOFILL_MODE="yes"
      shift
      ;;
    --no-autofill-api-key|--no-fill-browser)
      AUTOFILL_MODE="no"
      shift
      ;;
    --skip-prompts|--yes)
      SKIP_PROMPTS=1
      FORWARD_ARGS+=(--skip-prompts)
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --skip-keys)
      SKIP_KEYS=1
      FORWARD_ARGS+=(--skip-keys)
      shift
      ;;
    --ollama-model)
      FORWARD_ARGS+=(--ollama-model "${2:?--ollama-model requires a tag}")
      shift 2
      ;;
    --skip-install|--skip-python-deps|--skip-ollama|--skip-index|--skip-privacy|\
    --no-fsconnect|--no-profile-edit|--no-path-edit|--grok-dummy|--rotate-key|\
    --small-model|--ollama-install-script)
      FORWARD_ARGS+=("$1")
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1 (run with --help)"
      ;;
  esac
done

confirm() {
  # $1 prompt, $2 default y|n
  local prompt="$1"
  local default="${2:-y}"
  local reply=""

  if [ "$SKIP_PROMPTS" -eq 1 ]; then
    [ "$default" = "y" ]
    return $?
  fi

  if [ "$default" = "y" ]; then
    printf '[cyclaw-onboard] %s [Y/n] ' "$prompt" >&2
  else
    printf '[cyclaw-onboard] %s [y/N] ' "$prompt" >&2
  fi
  IFS= read -r reply || true
  case "$reply" in
    "")
      [ "$default" = "y" ]
      ;;
    y|Y|yes|YES|Yes)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

looks_like_repo() {
  [ -f "$1/gate.py" ] &&
  [ -f "$1/macos/setup-from-clone.sh" ] &&
  [ -f "$1/macos/setup-cyclaw-keys.sh" ] &&
  [ -f "$1/macos/invoke-cyclaw.sh" ]
}

absolute_dir() {
  (CDPATH= cd -- "$1" && pwd)
}

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_DIR=""

find_checkout() {
  local candidate=""

  if [ -n "$REPO_OVERRIDE" ]; then
    [ -d "$REPO_OVERRIDE" ] || die "--repo path does not exist: $REPO_OVERRIDE"
    looks_like_repo "$REPO_OVERRIDE" ||
      die "--repo does not look like CyClaw (missing gate.py or macos helpers): $REPO_OVERRIDE"
    REPO_DIR="$(absolute_dir "$REPO_OVERRIDE")"
    return 0
  fi

  for candidate in \
    "${CYCLAW_REPO:-}" \
    "$PWD" \
    "$SCRIPT_DIR/.." \
    "$CLONE_DIR"
  do
    [ -n "$candidate" ] || continue
    [ -d "$candidate" ] || continue
    if looks_like_repo "$candidate"; then
      REPO_DIR="$(absolute_dir "$candidate")"
      return 0
    fi
  done

  return 1
}

clone_checkout() {
  if [ "$DRY_RUN" -eq 1 ]; then
    REPO_DIR="$CLONE_DIR"
    step "dry-run: would clone https://github.com/CGFixIT/CyClaw.git into $REPO_DIR"
    return 0
  fi

  command -v git >/dev/null 2>&1 ||
    die "git is required. On macOS, run 'xcode-select --install', then retry."

  if [ -e "$CLONE_DIR" ]; then
    if [ -d "$CLONE_DIR" ] && ! looks_like_repo "$CLONE_DIR"; then
      die "clone destination '$CLONE_DIR' exists but is not a usable CyClaw checkout. Move it aside, or re-run with --repo PATH to use an existing checkout or --clone-dir PATH to pick a different destination."
    fi
    die "clone destination already exists but is not a usable CyClaw checkout: $CLONE_DIR. Re-run with --repo PATH or --clone-dir PATH."
  fi

  mkdir -p "$(dirname -- "$CLONE_DIR")"
  step "cloning CyClaw into $CLONE_DIR"
  git clone --branch main --single-branch https://github.com/CGFixIT/CyClaw.git "$CLONE_DIR"
  looks_like_repo "$CLONE_DIR" ||
    die "clone completed but required CyClaw files were not found"
  REPO_DIR="$(absolute_dir "$CLONE_DIR")"
}

if ! find_checkout; then
  if [ "$SKIP_PROMPTS" -eq 1 ]; then
    clone_checkout
  elif confirm "No CyClaw checkout was found. Clone it into '$CLONE_DIR'?" "y"; then
    clone_checkout
  else
    die "no checkout selected. Re-run with --repo PATH or --clone-dir PATH."
  fi
fi

# The underlying installer has its own platform gate. This early check fails
# faster for the standalone path, but is bypassable only for test harnesses.
if [ "${CYCLAW_ONBOARDING_SKIP_PLATFORM:-}" != "1" ]; then
  [ "$(uname -s)" = "Darwin" ] ||
    die "this onboarding script targets macOS (uname -s reported $(uname -s))"
  [ "$(uname -m)" = "arm64" ] ||
    die "Apple Silicon arm64 is required (this machine reported $(uname -m))"

  MACOS_VERSION="$(sw_vers -productVersion 2>/dev/null || true)"
  MACOS_MAJOR="${MACOS_VERSION%%.*}"
  if [ -n "$MACOS_MAJOR" ] && [ "$MACOS_MAJOR" -lt 14 ] 2>/dev/null; then
    die "macOS 14 Sonoma or newer is required (detected ${MACOS_VERSION:-unknown})"
  fi
fi

if [ "$SKIP_PROMPTS" -eq 0 ] && [ "$DRY_RUN" -eq 0 ] && [ ! -t 0 ]; then
  die "interactive onboarding needs a Terminal TTY. Re-run in Terminal or pass --skip-prompts."
fi

# Capture the choices before the long install begins, as requested. This lets
# the operator decide once and walk away while Python, Ollama, and the index do
# their usual impression of geological time.
if [ "$START_MODE" = "ask" ]; then
  if [ "$SKIP_PROMPTS" -eq 1 ]; then
    START_MODE="no"
  elif confirm "Start the CyClaw gateway when setup finishes?" "y"; then
    START_MODE="yes"
  else
    START_MODE="no"
  fi
fi

if [ "$START_MODE" = "yes" ] && [ "$BROWSER_MODE" = "ask" ]; then
  if [ "$SKIP_PROMPTS" -eq 1 ]; then
    BROWSER_MODE="no"
  elif confirm "Open the local terminal console in your browser?" "y"; then
    BROWSER_MODE="yes"
  else
    BROWSER_MODE="no"
  fi
elif [ "$BROWSER_MODE" = "ask" ]; then
  BROWSER_MODE="no"
fi

if [ "$START_MODE" = "yes" ] && [ "$BROWSER_MODE" = "yes" ] && [ "$AUTOFILL_MODE" = "ask" ]; then
  if [ "$SKIP_PROMPTS" -eq 1 ]; then
    AUTOFILL_MODE="no"
  elif confirm "Auto-populate the generated CyClaw API key in both local console key fields?" "y"; then
    AUTOFILL_MODE="yes"
  else
    AUTOFILL_MODE="no"
  fi
elif [ "$AUTOFILL_MODE" = "ask" ]; then
  AUTOFILL_MODE="no"
fi

if [ "$AUTOFILL_MODE" = "yes" ] && { [ "$START_MODE" != "yes" ] || [ "$BROWSER_MODE" != "yes" ]; }; then
  warn "API-key autofill requires both --start and browser opening; disabling autofill."
  AUTOFILL_MODE="no"
fi

echo ""
step "CyClaw macOS onboarding plan"
step "checkout      : $REPO_DIR"
step "start servers : $START_MODE"
step "open browser  : $BROWSER_MODE"
step "autofill key  : $AUTOFILL_MODE"
step "key contract  : autogenerated CYCLAW_API_KEY -> Keychain + 0600 dotenv"
echo ""

if [ "$DRY_RUN" -eq 1 ]; then
  step "dry-run only; no writes or network actions will occur"
  echo "  1. Run macos/setup-from-clone.sh --no-start"
  echo "  2. Existing key helper generates and persists CYCLAW_API_KEY"
  echo "  3. Existing helper asks for Telegram, Anthropic, Grok, and GitHub tokens"
  if [ "$START_MODE" = "yes" ]; then
    echo "  4. Start gateway :8787"
    [ "$BROWSER_MODE" = "yes" ] && echo "  5. Open the loopback console"
    [ "$AUTOFILL_MODE" = "yes" ] &&
      echo "  6. Fill #apiKeyInput in browser memory only"
  else
    echo "  4. Stop after installation/configuration"
  fi
  exit 0
fi

SETUP_ARGS=(--no-start)
SETUP_ARGS+=("${FORWARD_ARGS[@]}")

step "running the repository's canonical Apple Silicon setup"
bash "$REPO_DIR/macos/setup-from-clone.sh" "${SETUP_ARGS[@]}"

HOME_DIR="${CYCLAW_HOME:-$HOME/.CyClaw}"
ENV_FILE="$HOME_DIR/.env"

# xtrace would print every assignment while sourcing the dotenv. Refuse rather
# than turning a convenience flag into a credential-disclosure feature.
_dotenv_mode() {
  if [ "$(uname -s)" = "Darwin" ]; then
    # Pin BSD stat: a GNU stat earlier on PATH interprets -f differently,
    # so valid private dotenv files could fail the permission check.
    /usr/bin/stat -f %Lp "$1" 2>/dev/null || true
  else
    stat -c %a "$1" 2>/dev/null || true
  fi
}

_source_dotenv() {
  local f="$1"
  local mode=""
  [ -f "$f" ] || return 1
  mode="$(_dotenv_mode "$f")"
  case "$mode" in
    600|400) ;;
    *)
      # Name the file and the remedy. Without them the operator sees only a
      # mode number here and "CYCLAW_API_KEY not set" below, and the actual
      # cause -- a dotenv other local accounts can read -- goes unstated.
      echo "[cyclaw] warn : refusing to source $f (mode ${mode:-unknown}; want 600 or 400). Fix with: chmod 600 $f" >&2
      return 1
      ;;
  esac
  # Preserve source failure across export-state cleanup so the caller can
  # try the repo dotenv when loading the preferred file fails.
  # shellcheck disable=SC1090
  local source_status=0
  local had_allexport=0
  case "$-" in *a*) had_allexport=1 ;; esac
  set -a
  . "$f" || source_status=$?
  # Restore the caller's export policy; an unconditional set +a would disable
  # a setting that may have been enabled before this helper was called.
  if [ "$had_allexport" -eq 0 ]; then
    set +a
  fi
  return "$source_status"
}

case "$-" in
  *x*)
    die "refusing to source $ENV_FILE while shell xtrace is enabled"
    ;;
esac

# Chained on the result, not `-f`: a refused HOME file must not shadow the repo copy.
_source_dotenv "$ENV_FILE" || _source_dotenv "$REPO_DIR/.env" || true

if [ -z "${CYCLAW_API_KEY:-}" ]; then
  if [ "$SKIP_KEYS" -eq 1 ]; then
    warn "CYCLAW_API_KEY is unset because --skip-keys was requested; protected routes will return 401."
  else
    die "CYCLAW_API_KEY was not available after setup. No server was started."
  fi
else
  step "CYCLAW_API_KEY is present and will be inherited by the servers"
fi

if [ "$START_MODE" != "yes" ]; then
  echo ""
  step "setup complete; servers were not started"
  step "later: source '$ENV_FILE' && bash '$REPO_DIR/macos/invoke-cyclaw.sh' --repo '$REPO_DIR'"
  exit 0
fi

GATE_PORT="${CYCLAW_GATE_PORT:-8787}"

require_port() {
  case "$2" in
    ''|*[!0-9]*)
      die "$1 must be numeric (got '$2')"
      ;;
  esac
  if [ "$2" -lt 1 ] || [ "$2" -gt 65535 ]; then
    die "$1 must be between 1 and 65535 (got '$2')"
  fi
}

require_port "CYCLAW_GATE_PORT" "$GATE_PORT"

RUNNER_PID=""
# Set only while fill_browser_key's secret-bearing temp dir exists, so an
# interrupt mid-autofill (Ctrl+C between mktemp and the closing rm -rf) still
# removes it instead of leaving a 0600 API-key file behind in $TMPDIR.
FILL_KEY_TMP_DIR=""

cleanup_runner() {
  if [ -n "$FILL_KEY_TMP_DIR" ] && [ -d "$FILL_KEY_TMP_DIR" ]; then
    rm -rf "$FILL_KEY_TMP_DIR"
    FILL_KEY_TMP_DIR=""
  fi
  if [ -n "$RUNNER_PID" ] && kill -0 "$RUNNER_PID" 2>/dev/null; then
    step "stopping CyClaw process tree"
    kill -TERM "$RUNNER_PID" 2>/dev/null || true
    wait "$RUNNER_PID" 2>/dev/null || true
  fi
  RUNNER_PID=""
}

on_signal() {
  local code="$1"
  trap - EXIT INT TERM
  cleanup_runner
  exit "$code"
}

trap cleanup_runner EXIT
trap 'on_signal 130' INT
trap 'on_signal 143' TERM

step "starting gateway :$GATE_PORT"
bash "$REPO_DIR/macos/invoke-cyclaw.sh" \
  --repo "$REPO_DIR" \
  --gate-port "$GATE_PORT" \
  --no-browser &
RUNNER_PID=$!

wait_for_url() {
  local label="$1"
  local url="$2"
  local attempts="${3:-60}"
  local i=1
  local rc=0

  while [ "$i" -le "$attempts" ]; do
    if ! kill -0 "$RUNNER_PID" 2>/dev/null; then
      wait "$RUNNER_PID" || rc=$?
      RUNNER_PID=""
      die "$label process exited before becoming ready (exit $rc)"
    fi
    if curl -sf --max-time 2 "$url" >/dev/null 2>&1; then
      step "$label ready: $url"
      return 0
    fi
    sleep 0.5
    i=$((i + 1))
  done

  warn "$label did not answer within $((attempts / 2)) seconds; continuing while it finishes starting"
  return 1
}

wait_for_url "gateway" "http://127.0.0.1:$GATE_PORT/health" 80 || true

open_consoles() {
  if ! command -v open >/dev/null 2>&1; then
    warn "open(1) is unavailable; browse to the URLs manually"
    return 1
  fi
  open "http://127.0.0.1:$GATE_PORT" >/dev/null 2>&1 || true
  step "opened the loopback console"
  return 0
}

copy_key_fallback() {
  local ttl=90
  [ -n "${CYCLAW_API_KEY:-}" ] || return 1
  command -v pbcopy >/dev/null 2>&1 || return 1

  printf '%s' "$CYCLAW_API_KEY" | pbcopy
  step "autofill fallback: copied CYCLAW_API_KEY to the pasteboard without printing it"
  (
    sleep "$ttl"
    if command -v pbpaste >/dev/null 2>&1; then
      current="$(pbpaste 2>/dev/null || true)"
      if [ "$current" = "$CYCLAW_API_KEY" ]; then
        printf '' | pbcopy
      fi
    fi
  ) >/dev/null 2>&1 &
  # Without this, the clearer is a job of THIS script's shell and receives
  # SIGHUP the moment the script exits (Ctrl+C, or simply reaching the end of
  # main after a --no-browser-less run) -- killing it before the sleep
  # finishes and leaving the API key sitting in the pasteboard indefinitely.
  # Matches setup-cyclaw-keys.sh's identical clipboard-clear job, which
  # disowns for the same reason (see test_setup_cyclaw_keys_disowns_clipboard_clear_job).
  disown
  step "pasteboard will clear in ${ttl}s if it still contains the key"
}

fill_browser_key() {
  local tmp_dir=""
  local secret_file=""
  local script_file=""
  local rc=0

  [ -n "${CYCLAW_API_KEY:-}" ] || {
    warn "cannot autofill because CYCLAW_API_KEY is unset"
    return 1
  }

  if ! command -v osascript >/dev/null 2>&1; then
    warn "osascript is unavailable; cannot perform memory-only browser autofill"
    copy_key_fallback || true
    return 1
  fi

  tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/cyclaw-browser-fill.XXXXXX")"
  chmod 700 "$tmp_dir"
  FILL_KEY_TMP_DIR="$tmp_dir"
  secret_file="$tmp_dir/api-key"
  script_file="$tmp_dir/fill.applescript"

  printf '%s' "$CYCLAW_API_KEY" > "$secret_file"
  chmod 600 "$secret_file"

  cat > "$script_file" <<'APPLESCRIPT'
on replaceText(findText, replaceWith, sourceText)
  set AppleScript's text item delimiters to findText
  set parts to text items of sourceText
  set AppleScript's text item delimiters to replaceWith
  set outputText to parts as text
  set AppleScript's text item delimiters to ""
  return outputText
end replaceText

on jsQuoted(sourceText)
  set escapedText to my replaceText("\\", "\\\\", sourceText)
  set escapedText to my replaceText("'", "\\'", escapedText)
  set escapedText to my replaceText(return, "\\r", escapedText)
  set escapedText to my replaceText(linefeed, "\\n", escapedText)
  return "'" & escapedText & "'"
end jsQuoted

on urlAllowed(rawURL, gatePort)
  if rawURL is missing value then return false
  set u to rawURL as text
  if u is "" then return false

  set prefixes to {¬
    "http://127.0.0.1:" & gatePort, ¬
    "http://[::1]:" & gatePort}

  repeat with p in prefixes
    set prefixText to p as text
    if u is prefixText then return true
    if u starts with (prefixText & "/") then return true
    if u starts with (prefixText & "?") then return true
    if u starts with (prefixText & "#") then return true
  end repeat
  return false
end urlAllowed

on run argv
  set secretPath to item 1 of argv
  set gatePort to item 2 of argv
  set secretValue to read POSIX file secretPath as «class utf8»

  set js to "(function(){const value=" & my jsQuoted(secretValue) & ";let count=0;['apiKeyInput','apiKey'].forEach(function(id){const el=document.getElementById(id);if(!el){return;}el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));count+=1;});return count;})()"
  set totalFilled to 0

  tell application "System Events"
    set chromeRunning to exists process "Google Chrome"
    set safariRunning to exists process "Safari"
  end tell

  if chromeRunning then
    try
      tell application "Google Chrome"
        repeat with w in windows
          repeat with t in tabs of w
            try
              if my urlAllowed(URL of t, gatePort) then
                set n to execute t javascript js
                try
                  set totalFilled to totalFilled + (n as integer)
                end try
              end if
            end try
          end repeat
        end repeat
      end tell
    end try
  end if

  if safariRunning then
    try
      tell application "Safari"
        repeat with w in windows
          repeat with t in tabs of w
            try
              if my urlAllowed(URL of t, gatePort) then
                set n to do JavaScript js in t
                try
                  set totalFilled to totalFilled + (n as integer)
                end try
              end if
            end try
          end repeat
        end repeat
      end tell
    end try
  end if

  if totalFilled is 0 then
    error "No eligible CyClaw key field was filled" number 2
  end if

  return totalFilled
end run
APPLESCRIPT
  chmod 600 "$script_file"

  if osascript "$script_file" "$secret_file" "$GATE_PORT" >/dev/null 2>&1; then
    step "filled the local terminal API-key field (memory only; reload clears it)"
    rc=0
  else
    warn "browser autofill failed. Safari/Chrome may require 'JavaScript from Apple Events' permission."
    copy_key_fallback || true
    rc=1
  fi

  rm -rf "$tmp_dir"
  FILL_KEY_TMP_DIR=""
  return "$rc"
}

if [ "$BROWSER_MODE" = "yes" ]; then
  open_consoles || true
  if [ "$AUTOFILL_MODE" = "yes" ]; then
    # Give the freshly opened tabs time to build their DOM before injection.
    sleep 1.8
    fill_browser_key || true
  fi
fi

echo ""
step "CyClaw is running"
step "terminal : http://127.0.0.1:$GATE_PORT"
step "Ctrl+C in this Terminal stops the server"
echo ""

RUN_RC=0
wait "$RUNNER_PID" || RUN_RC=$?
RUNNER_PID=""
trap - EXIT INT TERM
exit "$RUN_RC"
