"""Run status/output-only checks in a disposable gitless source mirror.

No verification-generated bytes are copied into the authoritative checkout.
Darwin confines writes with Seatbelt; Linux requires bubblewrap namespaces;
Windows refuses until a filesystem/network boundary is implemented.
"""

from __future__ import annotations

import shutil
import stat
import sys
import tempfile
import time
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

from agentic.executor.hard_sandbox import (
    MAX_OUTPUT_CHARS,
    HardSandbox,
    HardSandboxUnavailable,
    production_sandbox,
)
from utils.child_environment import child_environment
from utils.logger import audit_log
from utils.numbat_emitter import emit_numbat_command, redact_argv_for_numbat

DEFAULT_CHECK_TIMEOUT_SEC = 120


def _scrubbed_env() -> dict[str, str]:
    env = child_environment("verification")
    env.update(NO_PROXY="*", no_proxy="*", PIP_NO_INDEX="1", PYTHONDONTWRITEBYTECODE="1")
    return env


def _mirror_argv(argv: Sequence[str], source: Path, mirror: Path) -> tuple[str, ...]:
    """Rebase absolute in-checkout script/file arguments into the candidate."""
    result = []
    for arg in argv:
        path = Path(arg)
        if path.is_absolute() and path.is_relative_to(source):
            arg = str(mirror / path.relative_to(source))
        result.append(arg)
    return tuple(result)


def _mirror_ignore(deadline: float):
    """Ignore .git plus FIFOs/sockets/device nodes; raise TimeoutError past deadline."""

    def ignore(directory: str, names: list[str]) -> list[str]:
        if time.monotonic() > deadline:
            raise TimeoutError("verification mirror copy exceeded check timeout")
        skipped: list[str] = []
        for name in names:
            if name == ".git":
                skipped.append(name)
                continue
            path = Path(directory) / name
            try:
                mode = path.lstat().st_mode
            except OSError:
                skipped.append(name)
                continue
            if stat.S_ISFIFO(mode) or stat.S_ISSOCK(mode) or stat.S_ISCHR(mode) or stat.S_ISBLK(mode):
                skipped.append(name)
        return skipped

    return ignore


def _copy_worktree_mirror(source: Path, mirror: Path, *, timeout_sec: int) -> None:
    """Copy ``source`` into ``mirror`` within the check's timeout budget.

    FIFOs and other specials are skipped (they can hang ``copytree`` forever).
    Overruns raise ``TimeoutError``; other copy failures raise ``OSError``.
    """
    deadline = time.monotonic() + max(1, int(timeout_sec))
    shutil.copytree(
        source,
        mirror,
        symlinks=True,
        ignore=_mirror_ignore(deadline),
    )
    if time.monotonic() > deadline:
        raise TimeoutError("verification mirror copy exceeded check timeout")


@dataclass(frozen=True)
class Check:
    """One verification command. ``argv`` is the command only -- no cwd/env/shell."""

    name: str
    argv: tuple[str, ...]
    timeout_sec: int = DEFAULT_CHECK_TIMEOUT_SEC

    def __post_init__(self) -> None:
        if not self.name:
            raise ValueError("Check.name must be non-empty")
        if not self.argv:
            raise ValueError(f"Check {self.name!r}: argv must be non-empty")


@dataclass(frozen=True)
class CheckResult:
    """The outcome of running one ``Check``."""

    name: str
    exit_code: int
    ok: bool
    stdout: str = ""
    stderr: str = ""
    timed_out: bool = False


@dataclass(frozen=True)
class VerificationReport:
    """Aggregate outcome of a ``run_verification`` call."""

    ok: bool
    results: tuple[CheckResult, ...] = field(default_factory=tuple)

    def failed_names(self) -> tuple[str, ...]:
        return tuple(r.name for r in self.results if not r.ok)


def run_verification(
    worktree: Path,
    checks: Sequence[Check],
    *,
    config_path: str = "config.yaml",
    cfg: dict | None = None,
    sandbox: HardSandbox | None = None,
) -> VerificationReport:
    """Run every check against a fresh gitless copy inside a hard sandbox.

    Runs checks sequentially so a hung check's timeout is attributable to
    exactly one process. ``worktree`` must already exist. ``sandbox`` is for
    tests; production callers omit it and get :func:`production_sandbox`.
    An empty check list is vacuously ok and does not require a backend.
    """
    backend = sandbox
    if checks and backend is None:
        backend = production_sandbox()
    env = _scrubbed_env()
    results = []
    for check in checks:
        with tempfile.TemporaryDirectory(prefix="cyclaw-verification-") as temporary:
            mirror = Path(temporary) / "candidate"
            source = worktree.resolve()
            copy_started = time.monotonic()
            try:
                _copy_worktree_mirror(source, mirror, timeout_sec=check.timeout_sec)
            except TimeoutError as exc:
                result = CheckResult(
                    name=check.name,
                    exit_code=-1,
                    ok=False,
                    stdout="",
                    stderr=str(exc),
                    timed_out=True,
                )
                audit_log(
                    {
                        "event": "agentic_executor_mirror_copy",
                        "check": check.name,
                        "ok": False,
                        "timed_out": True,
                        "error": str(exc),
                    },
                    config_path=config_path,
                    cfg=cfg,
                )
                results.append(result)
                continue
            except OSError as exc:
                result = CheckResult(
                    name=check.name,
                    exit_code=-1,
                    ok=False,
                    stdout="",
                    stderr=f"mirror copy failed: {exc}",
                    timed_out=False,
                )
                audit_log(
                    {
                        "event": "agentic_executor_mirror_copy",
                        "check": check.name,
                        "ok": False,
                        "timed_out": False,
                        "error": str(exc),
                    },
                    config_path=config_path,
                    cfg=cfg,
                )
                results.append(result)
                continue
            audit_log(
                {
                    "event": "agentic_executor_mirror_copy",
                    "check": check.name,
                    "ok": True,
                    "timed_out": False,
                },
                config_path=config_path,
                cfg=cfg,
            )
            env["HOME"] = str(mirror)
            env["USERPROFILE"] = str(mirror)
            if backend is None:
                raise HardSandboxUnavailable("nonempty checks require a sandbox backend")
            # Mirror copy already consumed wall time from the same check budget.
            elapsed = time.monotonic() - copy_started
            remaining = max(1, int(check.timeout_sec - elapsed))
            outcome = backend.run(
                _mirror_argv(check.argv, source, mirror),
                cwd=mirror,
                env=env,
                timeout_sec=remaining,
            )
            result = CheckResult(
                name=check.name,
                exit_code=outcome.exit_code,
                ok=outcome.exit_code == 0 and not outcome.timed_out,
                stdout=outcome.stdout,
                stderr=outcome.stderr,
                timed_out=outcome.timed_out,
            )
            audit_log(
                {
                    "event": "agentic_executor_check_result",
                    "check": result.name,
                    "exit_code": result.exit_code,
                    "ok": result.ok,
                    "timed_out": result.timed_out,
                },
                config_path=config_path,
                cfg=cfg,
            )
            emit_numbat_command(
                redact_argv_for_numbat(list(check.argv)),
                exit_code=result.exit_code,
                tool_name="executor",
                actor="system",
                tags=["executor", result.name],
                artifact_type="executor",
                config_path=config_path,
                cfg=cfg,
            )
            results.append(result)
    return VerificationReport(ok=all(r.ok for r in results), results=tuple(results))


def default_checks(repo_root: Path | None = None) -> tuple[Check, ...]:
    """CyClaw's own three checks: pytest, ruff, and the invariant guard.

    These are CyClaw-specific defaults, not something ``run_verification``
    itself assumes -- the shipped ``agentic.repo`` default IS
    ``"cgfixit/CyClaw"`` (config.yaml), so the harness's own first target is
    its own repository, and these are exactly the three commands
    ``CLAUDE.md``'s own quality bar names. ``repo_root`` locates
    ``invariant-guard``'s script inside the worktree being verified (it must
    be the SAME worktree ``run_verification`` runs against, not this
    process's own checkout, or the guard checks the wrong tree); defaults to
    this repo's own root for convenience when verifying CyClaw against
    itself.
    """
    root = repo_root or Path(__file__).resolve().parent.parent.parent
    return (
        Check("pytest", (sys.executable, "-m", "pytest", "-q", "--tb=short")),
        Check("ruff", (sys.executable, "-m", "ruff", "check", "--select", "E,F,I,B,C4,UP,S", ".")),
        Check(
            "invariant_guard",
            (sys.executable, str(root / ".claude" / "skills" / "invariant-guard" / "check_invariants.py")),
        ),
    )


__all__ = [
    "DEFAULT_CHECK_TIMEOUT_SEC",
    "MAX_OUTPUT_CHARS",
    "Check",
    "CheckResult",
    "VerificationReport",
    "default_checks",
    "run_verification",
]
