"""Regenerate the ASCII-preserving probe fold from the pinned Unicode TR39 data."""
import hashlib
from pathlib import Path

SOURCE_SHA256 = "091c7f82fc39ef208faf8f94d29c244de99254675e09de163160c810d13ef22a"  # DevSkim: ignore DS173237 - public Unicode integrity digest, not a credential
source = Path(__file__).with_name("confusables-17.0.0.txt").read_bytes()
if hashlib.sha256(source).hexdigest() != SOURCE_SHA256:
    raise ValueError("Unexpected Unicode source digest")
mappings = {}
for line in source.decode("utf-8").splitlines():
    fields = line.split("#", 1)[0].strip().split(";")
    if len(fields) < 2:
        continue
    key = int(fields[0].strip(), 16)
    mappings[key] = "".join(chr(int(cp, 16)) for cp in fields[1].split())
# Preserve the existing ASCII regex vocabulary: TR39 itself maps m to rn,
# for example. Reverse an ASCII letter's skeleton only when it is unique.
reverse = {}
for cp in range(ord("A"), ord("z") + 1):
    if chr(cp).isalpha():
        reverse.setdefault(mappings.get(cp, chr(cp)), []).append(chr(cp))
folds = {}
for cp, value in mappings.items():
    if cp < 128:
        continue
    letters = reverse.get(value, [])
    folds[cp] = letters[0] if len(letters) == 1 else value
output = Path(__file__).resolve().parents[1] / "_unicode_confusables.py"
with output.open("w", encoding="utf-8") as handle:
    handle.write('"""Generated by unicode_data/generate.py; Unicode 17.0.0, Unicode License v3."""\n\n')
    handle.write("CONFUSABLE_FOLD: dict[int, str] = {\n")
    for cp, value in sorted(folds.items()):
        handle.write(f"    0x{cp:X}: {ascii(value)},\n")
    handle.write("}\n")
