"""rclone filter file generation for CyClaw corpus sync.

Produces cyclaw_filters.txt -- the file rclone reads (``--filter-from``) to
decide what to sync. The defaults are deliberately exclusive: anything not in
this denylist still syncs, but the things that MUST NOT sync are listed first.
rclone evaluates filters top-to-bottom, first match wins, so the most-specific
/ most-dangerous rules come first.

Why this matters (security posture, in priority order):

  1. data/personality/  -- soul.md and cyclaw_soul.db. Mirroring these is a
     silent-rewrite path: a stale soul.md on a second machine can clobber an
     evolved one without going through POST /soul/apply. Excluded by default;
     the override (include_soul=true) is loud.
  2. AI model weights (*.gguf, *.bin, *.safetensors, ...). Managed per machine.
  3. ChromaDB / BM25 indices and embedding caches. Rebuildable in seconds via
     `python -m retrieval.indexer`.
  4. Python virtualenv, __pycache__, .git. Use normal channels.
  5. Audit logs (logs/**, *.log, *.jsonl). Per-machine forensic record.
  6. Per-host secrets, credentials, and governed soul DB state.

rclone filter syntax (https://rclone.org/filtering/):
  '- pattern'   exclude   '+ pattern'   include
"""

from __future__ import annotations

from pathlib import Path

from sync.config import RcloneConfig

# The single soul-layer rule -- conditionally dropped when include_soul=true.
_SOUL_RULE = "- data/personality/**"

# Built-in hardened exclusions. Order matters -- most-specific first.
_HARDENED_EXCLUDES: list[str] = [
    # 1. Soul layer -- governed via POST /soul/apply only (opt-in to sync).
    _SOUL_RULE,
    # 2. AI model weights.
    "- *.gguf",
    "- *.bin",
    "- *.safetensors",
    "- *.onnx",
    "- *.pt",
    "- *.pth",
    # 3. Vector store + keyword index + embedding cache (rebuildable).
    "- index/**",
    "- .emb_cache/**",
    "- .chroma/**",
    # 4. Python and virtualenv noise.
    "- venv/**",
    "- .venv/**",
    "- env/**",
    "- __pycache__/**",
    "- *.pyc",
    "- *.pyo",
    "- *.egg-info/**",
    # 5. Local forensic data -- never share across machines.
    "- logs/**",
    "- *.log",
    "- *.jsonl",
    # 6. Per-host secrets and credentials -- defense in depth.
    "- .env",
    "- .env.*",
    "- *.env",
    "- *.pem",
    "- *.key",
    "- *_secret*",
    "- credentials*",
    # 7. Governed soul DB state.
    "- *.db",
    "- *.db-wal",
    "- *.db-shm",
    # 8. VCS metadata (use git push/pull).
    "- .git/**",
    "- .gitignore",
    # 9. OS / editor metadata.
    "- .DS_Store",
    "- Thumbs.db",
    "- desktop.ini",
    "- *.swp",
    "- .idea/**",
    "- .vscode/**",
    # 10. rclone state (avoid recursive sync of state into Dropbox).
    "- .rclone-state/**",
    "- *.rclone.lst",
    "- *.rclone.lst-new",
    "- *.rclone.lst-prev",
]

_HEADER = """# CyClaw rclone filter file
# Auto-generated by sync.filters -- DO NOT EDIT BY HAND.
# To customise: add `extra_excludes` to the sync: block in config.yaml.
# Format: rclone filter rules -- '-' excludes, '+' includes, first match wins.
# https://rclone.org/filtering/
"""

_SOUL_WARNING = [
    "# WARNING: include_soul=true -- data/personality/ IS being synced.",
    "#          This bypasses POST /soul/apply governance. Stale soul.md on a",
    "#          second machine can silently clobber an evolved one. See config.yaml.",
]


def generate_filters(cfg: RcloneConfig) -> str:
    """Return the full text content of cyclaw_filters.txt for the given config."""
    lines: list[str] = [_HEADER.rstrip(), ""]

    excludes = list(_HARDENED_EXCLUDES)
    if cfg.include_soul:
        # Drop the data/personality/** rule (and only that one) so the soul
        # layer is mirrored. Loud, opt-in, discouraged.
        excludes = [e for e in excludes if e != _SOUL_RULE]
        lines.extend(_SOUL_WARNING)
        lines.append("")

    lines.extend(excludes)

    # User-supplied extras come AFTER the hardened block so users can tighten
    # further but cannot accidentally re-include something already excluded
    # (first-match-wins means a hardened rule already matched).
    if cfg.extra_excludes:
        lines.append("")
        lines.append("# --- extra_excludes from config.yaml ---")
        for raw in cfg.extra_excludes:
            pat = raw.strip()
            if not pat:
                continue
            # Tolerate entries written without a leading '- '.
            if not pat.startswith(("- ", "+ ", "!")):
                pat = f"- {pat}"
            lines.append(pat)

    return "\n".join(lines) + "\n"


def write_filter_file(cfg: RcloneConfig) -> str:
    """Generate cyclaw_filters.txt at cfg.filter_file; return the absolute path."""
    target = Path(cfg.filter_file or "")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(generate_filters(cfg), encoding="utf-8")
    return str(target.resolve())


def filter_summary(cfg: RcloneConfig) -> dict:
    """Return a small dict describing the active filter posture (for status/test)."""
    rules = [r for r in generate_filters(cfg).splitlines() if r and not r.startswith("#")]
    return {
        "soul_excluded": not cfg.include_soul,
        "include_soul": cfg.include_soul,
        "total_rules": len(rules),
        "filter_file": cfg.filter_file,
        "extra_excludes": list(cfg.extra_excludes),
    }
